# 1. Repository configuration
repository:
  id: 1
  name: MLTemplate
  description: A template repository for machine learning projects
  fullpath: /home/gom/Workspace/MLTemplate

# 2. Environment
environment:
  env_path: null

# 3. Data configuration
data:
  input_shape: (28, 28, 1)
  num_classes: 1
  train_data_path: /path/to/train_data
  validation_data_path: /path/to/validation_data

# 4. Model architecture
model:
  type: neural_network
  architecture: 
    - type: dense
      units: 128
      activation: relu
    - type: dropout
      rate: 0.2
    - type: dense
      units: 64
      activation: relu
    - type: dense
      units: 1
      activation: sigmoid

# 5. Training hyperparameters
training:
  batch_size: 64
  epochs: 10
  learning_rate: 0.001
  loss_function: binary_crossentropy
  optimizer: adam

# 6. Callbacks
callbacks:
  - type: early_stopping
    patience: 3
  - type: model_checkpoint
    filepath: /path/to/save/model_checkpoint.h5

# 7. Additional configurations
other_options:
  use_gpu: true
  random_seed: 42
